from flask import Flask, request, render_template
import openai
openai.api_key = "YOUR_API_KEY_HERE" # (DO NOT SHARE!) Use your API key form https://platform.openai.com/account

app = Flask(__name__)

# Define the OpenAI GPT-3 model to use for generating responses
model_engine = "text-davinci-003" #"text-davinci-002"

# Define the index page for the web application
@app.route('/')
def index():
    return render_template('index.html')

# Define the route for handling user input and generating a response
@app.route('/chat', methods=['POST'])
def chat():
    # Get the user's input from the form data
    user_input = request.form['user_input']

    # Generate a response based on the user's input
    response = generate_response(user_input)

    # Return the response as a JSON object
    return {'response': response}

# Define a function to generate a response based on the user's input
def generate_response(prompt):
    # Define the maximum length of the response generated by the model
    # be careful with max tokens if you have paid account
    max_tokens = 100

    # Define the OpenAI API request to generate a response based on the prompt
    response = openai.Completion.create(
        engine=model_engine,
        prompt=prompt,
        max_tokens=max_tokens
    )

    # Return the response generated by the model
    return response.choices[0].text

if __name__ == '__main__':
    app.run(debug=True)
